Exercise 2.2

diff --git a/the_project/apps/todo/Dockerfile b/the_project/apps/todo/Dockerfile
--- a/the_project/apps/todo/Dockerfile
+++ b/the_project/apps/todo/Dockerfile
@@ -1,29 +1,56 @@
-# Build stage
-FROM node:24-alpine AS builder
+FROM node:24-alpine AS base
 
+# 1. Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine 
+# for why libc6-compat is needed for shared library compatibility in Alpine.
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-COPY package*.json ./
-RUN npm ci
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
+
+# 2. Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-RUN npm run build
 
-# Production stage
-FROM node:24-alpine
+# Next.js collects completely anonymous telemetry data about general usage.
+ENV NEXT_TELEMETRY_DISABLED=1
 
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+
+# 3. Production runner
+FROM base AS runner
 WORKDIR /app
 
-COPY package*.json ./
-RUN npm ci --only=production && npm cache clean --force
+ENV NODE_ENV=production
+ENV NEXT_TELEMETRY_DISABLED=1
 
-COPY --from=builder /app/dist ./dist
-COPY --from=builder /app/views ./views
-COPY --from=builder /app/public ./public
-
-# Create cache directory for PVC mount
+# Create cache dir and ensure the default 'node' user has permissions
 RUN mkdir -p /app/cache && chown node:node /app/cache
+ENV IMAGE_CACHE_DIR=/app/cache
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder /app/public ./public
+COPY --from=builder /app/.next/standalone ./
+COPY --from=builder /app/.next/static ./.next/static
 
 USER node
 
-CMD ["node", "dist/app.js"]
+CMD ["node", "server.js"]
